name: Gray Scale Image Converter
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Build-Software:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "This job is done in the following branch ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: bash build.sh -m deploy
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."