name: Gray Scale Image Converter
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Build-Software:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "This job is done in the following branch ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: |
          pwd
          pip install -r requiments.txt
          echo "STATUS: Test source file..."
          if [ ! -d ${TARGET_DIR} ]; then mkdir ${TARGET_DIR}; fi
          python main_test.py
          echo "STATUS: Build executable file..."
          cp -r ./main/src/main.py ./target/grayscale_image_converter.py
          cd /target/
          pyinstaller grayscale_image_converter.py -y
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."