name: Build
run-name: ${{ github.event.head_commit.message }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install requiments
        run: |
          pip install -r ./main/src/requiments.txt
      - name: Test the source code
        run: |
          if [ ! -d ./target ]; then mkdir ./target; fi
          cd ./main/test/
          python main_test.py
      - name: Building exe file
        run: |
          cp -r ./main/src/main.py ./target/grayscale_image_converter.py
          cd target
          pyinstaller grayscale_image_converter.py -y
      - name: Deploy artifacts
        run: |
          echo "Deploy artifacts: to be done"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}."
